### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by morjanmihail** [iamntz/acf-gallery-wpml-fix#1]
Hello,

  For me is not working, I don't know if something is outdated or somewhere is my fault, but after I clone a post, the gallery from the new post still have the images with old ID's with the default language caption & title.

Kind regards,
Mihai

**Comment by iamntz** [comment]
Thanks for reporting. 

Unfortunately, I can't test it right now. As soon as I get home I'll check and see. Meanwhile, can you provide some extra info:
- acf version (stable, dev?)
- wpml version (and which wpml plugins you have installed)
- WordPress version

If all of these are the latest, can you also provide a minimum ACF export to be able to replicate?

Also, can you confirm that the problem is still present if you disable all other plugins, switch to default theme etc?
